# Model Evaluation

* r^2 ( r-squared) coefficient of determination 
* Mean Absolute error (MAE)
* Mean Squared Error(MSE)

In [1]:
print('Model EValuation')

Model EValuation

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# Load the data

heart_disease = pd.read_csv('data/heart.csv')
heart_disease.head(4)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [5]:
np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# fit the model
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [6]:
# Score the model

model.score(X_test, y_test)

0.940995669141443

In [7]:
# Model Evaluation 1. r2_score
from sklearn.metrics import r2_score

# Fill an array with the y_test mean
y_test_mean = np.full(len(y_test), y_test.mean())

y_test_mean

array([0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902,
       0.50243902, 0.50243902, 0.50243902, 0.50243902, 0.50243902])

In [8]:

r2_score(y_true=y_test, y_pred=y_test_mean)

0.0

In [9]:
r2_score(y_true=y_test, y_pred=y_test)

1.0

In [10]:
# MAE (Mean Absolute Error)

from sklearn.metrics import mean_absolute_error

y_preds = model.predict(X_test)
mae = mean_absolute_error(y_test, y_preds)
mae

0.059853658536585364

In [11]:
y_preds

array([0.98, 0.72, 0.  , 1.  , 0.  , 0.98, 0.05, 0.  , 0.98, 0.  , 0.85,
       0.  , 1.  , 0.86, 0.  , 0.1 , 0.  , 1.  , 0.96, 0.  , 0.28, 0.  ,
       0.12, 0.  , 0.28, 1.  , 0.94, 1.  , 0.02, 0.16, 0.03, 0.9 , 0.12,
       0.72, 0.99, 1.  , 0.28, 0.97, 0.98, 1.  , 0.  , 0.  , 0.88, 0.12,
       0.  , 0.01, 0.01, 0.02, 0.02, 0.86, 0.91, 0.  , 0.26, 0.01, 0.94,
       0.98, 0.01, 0.  , 0.26, 1.  , 0.92, 0.99, 0.02, 0.86, 0.  , 0.04,
       0.99, 0.05, 0.01, 0.98, 0.21, 0.02, 0.  , 1.  , 1.  , 0.96, 0.05,
       0.03, 0.13, 1.  , 0.  , 0.  , 0.01, 0.  , 0.94, 0.  , 0.85, 0.02,
       0.  , 0.16, 0.06, 0.  , 0.97, 1.  , 0.98, 0.99, 0.05, 0.03, 0.  ,
       0.  , 0.84, 0.05, 0.09, 0.96, 0.  , 0.98, 0.  , 0.96, 0.  , 0.98,
       0.26, 0.98, 1.  , 0.  , 0.97, 0.98, 0.1 , 0.96, 0.88, 0.  , 0.95,
       0.81, 0.  , 0.01, 0.89, 0.  , 0.96, 0.03, 0.21, 1.  , 0.9 , 0.  ,
       0.98, 0.84, 0.  , 1.  , 0.  , 0.81, 1.  , 0.1 , 0.98, 0.93, 1.  ,
       0.87, 0.97, 0.9 , 0.91, 1.  , 0.12, 0.  , 0.12, 0.01, 0.99, 0.98,
       0.  , 0.  , 0.11, 1.  , 0.05, 0.  , 0.88, 0.97, 0.05, 0.05, 0.95,
       0.91, 0.  , 0.01, 0.9 , 1.  , 0.  , 0.97, 0.98, 0.  , 0.96, 0.72,
       0.99, 0.  , 0.09, 1.  , 1.  , 0.03, 1.  , 0.26, 0.88, 0.88, 0.99,
       0.26, 0.91, 0.99, 1.  , 0.13, 0.  , 0.26, 0.  , 0.85, 0.05, 0.01,
       1.  , 1.  , 0.88, 0.98, 1.  , 0.  , 0.02])

In [12]:
result_data = pd.DataFrame(data = {
    "actual values": y_test,
    "predicted values": y_preds
    })

result_data['differences'] = result_data['predicted values'] - result_data['actual values']


result_data

     actual values  predicted values  differences
527              1              0.98        -0.02
359              1              0.72        -0.28
447              0              0.00         0.00
31               1              1.00         0.00
621              0              0.00         0.00
..             ...               ...          ...
832              1              0.88        -0.12
796              1              0.98        -0.02
644              1              1.00         0.00
404              0              0.00         0.00
842              0              0.02         0.02

[205 rows x 3 columns]

In [13]:
result_data['differences'].mean()

-0.014097560975609774

In [14]:
np.abs(result_data['differences']).mean()

0.059853658536585294

In [15]:
result_data['absolute difference'] = np.abs(result_data['differences'])
result_data.head()

     actual values  predicted values  differences  absolute difference
527              1              0.98        -0.02                 0.02
359              1              0.72        -0.28                 0.28
447              0              0.00         0.00                 0.00
31               1              1.00         0.00                 0.00
621              0              0.00         0.00                 0.00

In [16]:
result_data['absolute difference'].mean()  # Mean absolute error

0.059853658536585294

In [17]:
# Evaluating the model with MSE(Mean squared Error)
# The square of the errors between the actual and predicted values


from sklearn.metrics import mean_squared_error
y_preds = model.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
mse

0.01475073170731707

In [18]:
result_data['squared differences'] = np.square(result_data['differences'])
result_data.head()

,actual values,predicted values,differences,absolute difference,squared differences
527,1,0.98,-0.02,0.02,0.0004
359,1,0.72,-0.28,0.28,0.0784
447,0,0.00,0.00,0.00,0.0000
31,1,1.00,0.00,0.00,0.0000
621,0,0.00,0.00,0.00,0.0000

In [19]:
result_data['squared differences'].mean()

0.014750731707317076

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

clf = RandomForestClassifier()

In [21]:
np.random.seed(42)

cv_accuracy = cross_val_score(clf, X, y, cv=5, scoring=None)
cv_accuracy

print(np.mean(cv_accuracy))

0.9970731707317073

In [22]:
# Precision
cv_procision = cross_val_score(clf, X, y, cv=5, scoring='precision')
cv_procision

array([1.        , 1.        , 0.97222222, 1.        , 0.97247706])

In [23]:
print(f'Precision scoring {np.mean(cv_procision) * 100}')

Precision scoring 98.89398572884811

In [24]:
# Recall
cv_recall = cross_val_score(clf, X, y, cv=5, scoring='recall')
cv_recall
print(f'Recall scoring {np.mean(cv_recall) * 100}')

Recall scoring 100.0

In [25]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV

In [26]:
np.random.seed(42)

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_preds = model.predict(X_test)

#Evaluate and score the model

print(f'The Accuracy Score is {accuracy_score(y_test, y_preds) *100: .2f}')
print(f'The Precision Score is {precision_score(y_test, y_preds)}')
print(f'The Recall Score is {recall_score(y_test, y_preds)}')
print(f'The F1 Score is {f1_score(y_test, y_preds)}')

The Accuracy Score is  98.54
The Precision Score is 1.0
The Recall Score is 0.970873786407767
The F1 Score is 0.9852216748768473

In [27]:
# Evaluation
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

regressor_model = RandomForestRegressor()
regressor_model.fit(X_train, y_train)

y_preds = regressor_model.predict(X_test)

print(f'R2 score {r2_score(y_test, y_preds)}')
print(f'The Mean absolute Error score {mean_absolute_error(y_test, y_preds)}')
print(f'The Mean Squared Error {mean_squared_error(y_test, y_preds)}')

R2 score 0.9330715781458214
The Mean absolute Error score 0.06019512195121952
The Mean Squared Error 0.016731707317073175

In [28]:

grid = {'n_estimators': [205, 820]}
grid_search_cv = GridSearchCV(estimator=regressor_model,
                            param_grid=grid,
                            n_jobs=10, cv=5, verbose=5)

grid_search_cv.fit(X_train, y_train)
y_pred = grid_search_cv.predict(X_test)
y_pred

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV 5/5] END ..................n_estimators=205;, score=0.808 total time=   0.4s
[CV 1/5] END ..................n_estimators=205;, score=0.949 total time=   0.4s
[CV 2/5] END ..................n_estimators=205;, score=0.857 total time=   0.4s
[CV 3/5] END ..................n_estimators=205;, score=0.956 total time=   0.4s
[CV 4/5] END ..................n_estimators=205;, score=0.929 total time=   0.4s
[CV 4/5] END ..................n_estimators=820;, score=0.933 total time=   1.2s
[CV 1/5] END ..................n_estimators=820;, score=0.954 total time=   1.2s
[CV 2/5] END ..................n_estimators=820;, score=0.866 total time=   1.2s
[CV 3/5] END ..................n_estimators=820;, score=0.957 total time=   1.2s
[CV 5/5] END ..................n_estimators=820;, score=0.802 total time=   1.2s

array([0.98658537, 0.76219512, 0.        , 0.99512195, 0.00121951,
       0.96341463, 0.06463415, 0.00121951, 0.99512195, 0.00609756,
       0.83170732, 0.00365854, 0.99512195, 0.93658537, 0.00121951,
       0.10121951, 0.        , 1.        , 0.97926829, 0.        ,
       0.26707317, 0.        , 0.08780488, 0.00121951, 0.26707317,
       1.        , 0.95731707, 0.99634146, 0.00609756, 0.11829268,
       0.02317073, 0.91829268, 0.10853659, 0.76219512, 0.98658537,
       0.99634146, 0.26707317, 0.95      , 0.96707317, 1.        ,
       0.00121951, 0.00365854, 0.8695122 , 0.08780488, 0.        ,
       0.01585366, 0.02560976, 0.04268293, 0.0304878 , 0.84512195,
       0.93170732, 0.        , 0.2695122 , 0.00243902, 0.95731707,
       0.96707317, 0.02195122, 0.        , 0.33658537, 0.99878049,
       0.92560976, 0.97073171, 0.00609756, 0.84512195, 0.00365854,
       0.02195122, 1.        , 0.09878049, 0.01585366, 0.97682927,
       0.18780488, 0.00609756, 0.01097561, 0.99634146, 0.98414634,
       0.9597561 , 0.06463415, 0.1       , 0.11097561, 1.        ,
       0.00121951, 0.00487805, 0.01463415, 0.        , 0.94146341,
       0.        , 0.83170732, 0.03780488, 0.00121951, 0.11829268,
       0.02804878, 0.        , 0.96585366, 1.        , 0.98780488,
       0.99512195, 0.09878049, 0.02317073, 0.        , 0.        ,
       0.81829268, 0.07317073, 0.09390244, 0.92804878, 0.        ,
       0.98780488, 0.        , 0.96585366, 0.00609756, 0.98536585,
       0.33658537, 0.98536585, 1.        , 0.00365854, 0.98414634,
       0.96341463, 0.12439024, 0.98292683, 0.87804878, 0.        ,
       0.92073171, 0.82439024, 0.        , 0.00243902, 0.88170732,
       0.00121951, 0.96707317, 0.04146341, 0.18780488, 0.99390244,
       0.91829268, 0.        , 1.        , 0.81829268, 0.        ,
       0.9902439 , 0.00487805, 0.82439024, 0.9902439 , 0.12439024,
       0.96463415, 0.96097561, 1.        , 0.86463415, 0.97682927,
       0.95      , 0.93170732, 0.99634146, 0.12439024, 0.00121951,
       0.10853659, 0.01585366, 0.9804878 , 0.96463415, 0.00609756,
       0.        , 0.07317073, 0.99390244, 0.04634146, 0.00365854,
       0.8695122 , 0.97317073, 0.07317073, 0.07317073, 0.93658537,
       0.85      , 0.00609756, 0.02682927, 0.92560976, 0.99634146,
       0.01097561, 0.96219512, 0.98292683, 0.00121951, 0.97195122,
       0.76219512, 0.99512195, 0.00487805, 0.09390244, 0.99878049,
       0.99878049, 0.00365854, 1.        , 0.2695122 , 0.91097561,
       0.87804878, 0.98658537, 0.33658537, 0.93658537, 0.99390244,
       0.9804878 , 0.11097561, 0.00731707, 0.2695122 , 0.        ,
       0.87804878, 0.04512195, 0.00731707, 1.        , 1.        ,
       0.90609756, 0.97926829, 1.        , 0.        , 0.04878049])

In [ ]:
# Save the model

import pickle

pickle.dump(grid_search_cv, open('models/gs_random_forest_model.pkl', 'wb'))

In [31]:
# Load the model

loaded_pickle_model = pickle.load(open('models/gs_random_forest_model.pkl', 'rb'))
loaded_pickle_model

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=10,
             param_grid={'n_estimators': [205, 820]}, verbose=5)

In [32]:
# using the joblib

from joblib import dump, load

# save the model

dump(model, filename='models/random_forest_model.joblib')

['models/random_forest_model.joblib']

In [33]:
# Load the model

my_model = load(filename='models/random_forest_model.joblib')
my_model

RandomForestClassifier()

In [34]:
y_test = my_model.predict(X_test)
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0])